NNF-88 cppcheck and workflows

diff --git a/tools/hooks/pre-commit b/tools/hooks/pre-commit
--- a/tools/hooks/pre-commit
+++ b/tools/hooks/pre-commit
@@ -1,6 +1,17 @@
 #!/bin/sh
 
-# Uncrustify check
+# Cppcheck
+echo "pre-commit: Running cppcheck..."
+if ! cmake --build build -t cppcheck
+then
+    echo "pre-commit: Aborting commit due to failed cppcheck"
+    exit 1
+else
+    echo "pre-commit: Cppcheck passed"
+    exit 0
+fi
+
+# Uncrustify
 echo "pre-commit: Running uncrustify check..."
 if ! cmake --build build -t uncrustify-check
 then
